# Github forced settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false

kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-coffeescript
    - jekyll-paginate

# Site settings
title: Gilles Crettenand
author: Gilles Crettenand
email: gilles@crettenand.info
description: "My personnal homepage"

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://gilles.crettenand.info"
twitter_username: gcrettenand
github_username:  krtek4

permalink: /blog/:categories/:year/:month/:day/:title
excerpt_separator: <!--more-->

collections:
  portfolio:
    output: true
