# Site settings
title: Gilles Crettenand
email: gilles@crettenand.info
description: "My personnal homepage"

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://gilles.crettenand.info"
twitter_username: meierg
github_username:  krtek4

# Build settings
markdown: kramdown

permalink: /blog/:categories/:year/:month/:day/:title
excerpt_separator: <!--more-->

collections:
  portfolio:
    output: true
